### ISSUE TITLE
Баг/утечки памяти от слушателей событий

### ISSUE THREAD

**Issue by awqsomee** [ValeriaNigametzianova/Nebula-Extension#4]
1. Добавляешь слово игры, категорию игры
2. Открываешь google.com, с поиском игры
3. Ждешь
4. Опаньки..

**Comment by ValeriaNigametzianova** [comment]
Поправлено в [78fd5a4](https://github.com/ValeriaNigametzianova/Nebula-Extension/releases/tag/Nebula-Extension-v1.1.1)
